### ISSUE TITLE
ユーザーのリンクは登録任意にする

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-sponsorship#30]
ユーザー情報を登録した後に消去できるようにしておく。
リンクの登録がユーザー登録すると強制になってしまうので任意にする。

1. 表示名だけ入力すればリンクは空でも大丈夫にする。
2.ユーザー情報を登録した後にユーザー名を消去する機能を作る（空文字にする？）

**Comment by takonasu** [comment]
@szk18 できますか？？

**Comment by szk18** [comment]
やってみます、ダメだったら助けてください。

**Comment by takonasu** [comment]
天才、ありがとう！！ジュース奢ります

**Comment by szk18** [comment]
たしかにリンク入力が矯正なのは良くないね
![エンジニアを褒めるネコ:さすがです](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/04_%E3%81%95%E3%81%99%E3%81%8C%E3%81%A7%E3%81%99.png)
