### ISSUE TITLE
ログアウトができない

### ISSUE THREAD

**Issue by szk18** [twin-te/twinte-sponsorship#67]
たぶん現行のログアウトボタンが機能していないと思われ．
ログアウトに成功しました！ってアラート出るけど，ガッツリCookieが残っとる．

`store` のログアウト処理で，ログアウトのエンドポイントに向かってgetリクエスト飛ばしてるのがよくなくて，ログインのように `a` タグ使ってエンドポイントに飛ばす必要がある．

**Comment by szk18** [comment]
さっさか直そうと思ったが、nodeのバージョンが古いのかbuildに失敗するために放置しています。

**Comment by takonasu** [comment]
旧版（next.js）の問題なら修正せずに放置しておいていいかも、今新しい(Next.js)の作っているし

**Comment by szk18** [comment]
Next.js に移行したためclose
