### ISSUE TITLE
サブスク登録のラジオボタンの色とデフォルト選択の修正

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-sponsorship#75]
Twin:teカラーじゃないので、Twin:teカラーに変える

**Comment by szk18** [comment]
これ見てみたけど，うまくできないねぇ

**Comment by szk18** [comment]
サブスクのラジオボタンにデフォルトでチェック入れておきたい．いまは何も選択されてなくても，stripeに移動できて，そこでは200円のサブスクが選択されている

**Comment by szk18** [comment]
`input` に `checked={true}` って入れるとデフォルトで選択されるけど，選択したのと別のプランが選択される？ようなよくわからない挙動をするね

**Comment by szk18** [comment]
これかな
https://github.com/Wikiki/bulma-checkradio/issues/69

**Comment by takonasu** [comment]
> input に checked={true} って入れるとデフォルトで選択されるけど，選択したのと別のプランが選択される？ようなよくわからない挙動をするね

それな、なので別のradioコンポーネントの使用を検討したほうがいいのかなっておもってる

**Comment by szk18** [comment]
了解．挙動が変なのは考えればどうにかなるかもしれんけど，色の方は厳しいかもね．
`bulma-checkradio` を使わないという選択肢を考えるのは良いと思います

**Comment by takonasu** [comment]
デフォルトの挙動がおかしい問題これだった
https://ja.reactjs.org/docs/dom-elements.html

つまり、checked属性はReactでは別の意味をしていて、最初の選択肢として選ばせておくにはdefaultCheckedを使わないといけないとのこと、これで解決できた
