### ISSUE TITLE
登録情報とはなにかを説明する

### ISSUE THREAD

**Issue by szk18** [twin-te/twinte-sponsorship#8]
/mypage の"登録情報の変更"がよくわからないので、登録情報がどこでどのように使われるかの説明をする必要がありそう

**Comment by takonasu** [comment]
寄付者一覧に表示するお名前とリンクです。

っていう説明で十分かな？

**Comment by szk18** [comment]
十分だと思う、欲を言えば寄付者一覧のリンクを張ってあげるとどうやって使われているのかがわかって良さそう

**Comment by takonasu** [comment]
そうしようか〜
