### ISSUE TITLE
おそらくBE側のバグと思われるもの一覧

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-sponsorship#82]
このリポジトリではないが、忘れる前に逐次追加

- 寄付履歴の日付がおかしい
→おそらくBE側でUNIX時の解釈ミスってる
→対応策としてはそのままUNIX時返してくれればFEで対処できる
- successページへのリダイレクト時にtype,amountパラメータがない
→寄付金額や寄付種類を表示できない・ツイートできない
→BE側のリダイレクト時にGETパラメータを渡してあげる

**Comment by szk18** [comment]
@takonasu closeしちゃうねん
