### ISSUE TITLE
見た目

### ISSUE THREAD

**Issue by takonasu** [twin-te/twinte-sponsorship#94]
# 共通
- [x] #75  @takonasu
- [x] タイトルとアイコンの中心がずれている（気がする）@szk18
- [x] #96 @szk18
- [x] 手数料を差し引くといくら寄付されるかが表示されていない @takonasu 
- [x] サブスクの寄付ぼたんは「登録ボタン」に文言を変更 @szk18
- [x] ユーザー情報変更のボタンをfigmaに寄せる 
- [x] モーダルのレイアウトをfigmaに寄せる @szk18
- [x] 解約ボタンを囲まないようにする @szk18

# モバイル版
- [x] メニューボタンが小さい
- [x] 右上のログアウト・ログインボタンを白囲みする @szk18
- [ ] 寄付履歴のレイアウトをfigmaに寄せる @takonasu

**Comment by takonasu** [comment]
closeしてもよさそう

**Comment by szk18** [comment]
👌
